"""Add export settings to Resume model

Revision ID: 27081f99702c
Revises: a1f4c822f86c
Create Date: 2025-10-17 09:39:56.282118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27081f99702c'
down_revision: Union[str, Sequence[str], None] = 'a1f4c822f86c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('export_settings_include_projects', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('resumes', sa.Column('export_settings_render_projects_first', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('resumes', sa.Column('export_settings_include_education', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'export_settings_include_education')
    op.drop_column('resumes', 'export_settings_render_projects_first')
    op.drop_column('resumes', 'export_settings_include_projects')
    # ### end Alembic commands ###
