"""Add is_base, job_description, and parent_id to resumes

Revision ID: 3e902acf0d1d
Revises: 6d5a3e096652
Create Date: 2025-09-21 09:26:36.757359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e902acf0d1d'
down_revision: Union[str, Sequence[str], None] = '6d5a3e096652'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "resumes", sa.Column("is_base", sa.Boolean(), nullable=False, server_default="true")
    )
    op.add_column("resumes", sa.Column("job_description", sa.Text(), nullable=True))
    op.add_column('resumes', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'resumes', 'resumes', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resumes', type_='foreignkey')
    op.drop_column('resumes', 'parent_id')
    op.drop_column('resumes', 'job_description')
    op.drop_column('resumes', 'is_base')
    # ### end Alembic commands ###
