"""add llm_model_name to user_settings

Revision ID: 6d5a3e096652
Revises: e1213f020728
Create Date: 2025-09-02 15:32:17.937771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d5a3e096652'
down_revision: Union[str, Sequence[str], None] = 'e1213f020728'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('llm_model_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'llm_model_name')
    # ### end Alembic commands ###
