"""Add notes and introduction to Resume model

Revision ID: a1f4c822f86c
Revises: 3e902acf0d1d
Create Date: 2025-10-03 07:45:15.889605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1f4c822f86c'
down_revision: Union[str, Sequence[str], None] = '3e902acf0d1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('resumes', sa.Column('introduction', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'introduction')
    op.drop_column('resumes', 'notes')
    # ### end Alembic commands ###
