"""
Add last_login_at and force_password_change to user model

Revision ID: e1213f020728
Revises: e0c1a2b3d4f5
Create Date: 2025-08-30 20:15:41.289433

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e1213f020728"
down_revision: str | Sequence[str] | None = "e0c1a2b3d4f5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("last_login_at", sa.DateTime(), nullable=True))
    op.add_column(
        "users",
        sa.Column("force_password_change", sa.Boolean(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "force_password_change")
    op.drop_column("users", "last_login_at")
    # ### end Alembic commands ###
