import asyncio
import json
import logging
import re
from collections.abc import AsyncGenerator, Awaitable, Callable
from typing import Any

from cryptography.fernet import InvalidToken
from langchain_core.output_parsers import PydanticOutputParser, StrOutputParser
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.utils.json import parse_json_markdown
from langchain_openai import ChatOpenAI
from openai import AuthenticationError
from pydantic import ValidationError

from resume_editor.app.api.routes.route_logic.resume_serialization import (
    extract_experience_info,
)
from resume_editor.app.llm.models import (
    CandidateAnalysis,
    CrossSectionEvidence,
    GeneratedBanner,
    GeneratedIntroduction,
    JobAnalysis,
    JobKeyRequirements,
    LLMConfig,
    RefinedRole,
    RefinedRoleRecord,
    RoleRefinementJob,
    RunningLog,
)
from resume_editor.app.llm.prompts import (
    BANNER_GENERATION_HUMAN_PROMPT,
    BANNER_GENERATION_SYSTEM_PROMPT,
    INTRO_ANALYZE_JOB_HUMAN_PROMPT,
    INTRO_ANALYZE_JOB_SYSTEM_PROMPT,
    INTRO_ANALYZE_RESUME_HUMAN_PROMPT,
    INTRO_ANALYZE_RESUME_SYSTEM_PROMPT,
    INTRO_SYNTHESIZE_INTRODUCTION_HUMAN_PROMPT,
    INTRO_SYNTHESIZE_INTRODUCTION_SYSTEM_PROMPT,
    JOB_ANALYSIS_HUMAN_PROMPT,
    JOB_ANALYSIS_SYSTEM_PROMPT,
    ROLE_REFINE_HUMAN_PROMPT,
    ROLE_REFINE_SYSTEM_PROMPT,
)
from resume_editor.app.models.resume.experience import Role

log = logging.getLogger(__name__)


DEFAULT_LLM_TEMPERATURE = 0.2


def _parse_json_with_fix(json_string: str) -> Any:
    r"""Parse a JSON string, attempting to fix common LLM-produced errors.

    Specifically, this function handles `json.JSONDecodeError` caused by
    "Invalid \escape" by replacing single backslashes with double backslashes
    and retrying the parse.

    Args:
        json_string (str): The JSON string to parse.

    Returns:
        Any: The parsed Python object.

    Raises:
        json.JSONDecodeError: If parsing fails even after attempting a fix,
            or if the initial error is not an "Invalid \\escape" error.

    """
    try:
        return parse_json_markdown(json_string)
    except json.JSONDecodeError as e:
        if "Invalid \\escape" in str(e):
            _msg = "Attempting to fix invalid escape sequence in JSON string"
            log.debug(_msg)
            # Use a regex to replace backslashes that are not part of a valid JSON escape sequence.
            # This is a common issue with file paths in strings generated by LLMs.
            corrected_json_string = re.sub(r'\\(?!["\\/bfnrtu])', r"\\\\", json_string)
            try:
                return parse_json_markdown(corrected_json_string)
            except json.JSONDecodeError:
                raise e  # re-raise original exception
        else:
            raise e


def _unwrap_exception_group(e: Exception):
    """Unwraps an ExceptionGroup if it contains a single non-cancellation error.

    Args:
        e (Exception): The exception to inspect.

    Raises:
        The unwrapped exception if conditions are met, otherwise re-raises the
        original exception.

    Notes:
        1. If 'e' is not an ExceptionGroup, it is re-raised.
        2. If 'e' is an ExceptionGroup, it filters out any asyncio.CancelledError
           exceptions.
        3. If exactly one non-cancellation error remains, that single error is raised.
        4. Otherwise, the original ExceptionGroup is re-raised.

    """
    if isinstance(e, ExceptionGroup):
        # Filter out cancellation errors to find the root cause
        non_cancel_errors = [
            exc for exc in e.exceptions if not isinstance(exc, asyncio.CancelledError)
        ]
        if len(non_cancel_errors) == 1:
            raise non_cancel_errors[0]
    raise e


def _initialize_llm_client(llm_config: LLMConfig) -> ChatOpenAI:
    """Initializes the ChatOpenAI client from configuration.

    Args:
        llm_config (LLMConfig): Configuration for the LLM client.

    Returns:
        ChatOpenAI: An initialized ChatOpenAI client instance.

    Notes:
        1.  Determines the model name, using the provided `llm_model_name` or falling
            back to a default.
        2.  Sets up LLM parameters for temperature, endpoint, and headers (if OpenRouter
            is used).
        3.  Sets the API key if provided, or uses a dummy key if a custom endpoint is
            specified without a key.
        4.  Returns an initialized `ChatOpenAI` client.

    """
    model_name = llm_config.llm_model_name if llm_config.llm_model_name else "gpt-4o"
    llm_params: dict[str, Any] = {
        "model": model_name,
        "temperature": DEFAULT_LLM_TEMPERATURE,
    }
    if llm_config.llm_endpoint:
        llm_params["openai_api_base"] = llm_config.llm_endpoint
        if "openrouter.ai" in llm_config.llm_endpoint:
            llm_params["default_headers"] = {
                "HTTP-Referer": "http://localhost:8000/",
                "X-Title": "Resume Editor",
            }
    if llm_config.api_key:
        llm_params["api_key"] = llm_config.api_key
    elif llm_config.llm_endpoint and "openrouter.ai" not in llm_config.llm_endpoint:
        llm_params["api_key"] = "not-needed"

    return ChatOpenAI(**llm_params)


async def analyze_job_description(
    job_description: str,
    llm_config: LLMConfig,
    resume_content_for_context: str,
) -> tuple[JobAnalysis, str | None]:
    """Uses an LLM to analyze a job description.

    Args:
        job_description (str): The job description to analyze.
        llm_config (LLMConfig): LLM configuration including endpoint, API key, and model
            name.
        resume_content_for_context (str): The full resume content, used to provide
            context for the analysis.

    Returns:
        JobAnalysis: The structured analysis of the job description.

    Notes:
        1. Set up a `PydanticOutputParser` for structured output based on the
           `JobAnalysis` model.
        2. Prepare prompt components for with resume content for context.
        3. Create a `ChatPromptTemplate` with instructions for the LLM.
        4. Determine the model name, using the provided `llm_model_name` or falling
           back to a default.
        5. Initialize the `ChatOpenAI` client.
        6. Create a chain combining the prompt, LLM, and a `StrOutputParser`.
        7. Asynchronously invoke the chain with the job description and resume content.
        8. Parse the JSON response and validate it against the `JobAnalysis` model.
        9. Return the `JobAnalysis` object.

    Network access:
        - This function makes a network request to the LLM endpoint specified by
          llm_endpoint.

    """
    _msg = "analyze_job_description starting"
    log.debug(_msg)

    if not job_description.strip():
        raise ValueError("Job description cannot be empty.")

    parser = PydanticOutputParser(pydantic_object=JobAnalysis)

    # Conditionally prepare prompt components for introduction generation
    resume_content_block = (
        f"Resume Content:\n---\n{resume_content_for_context}\n---\n\n"
    )

    prompt = ChatPromptTemplate.from_messages(
        [
            ("system", JOB_ANALYSIS_SYSTEM_PROMPT),
            ("human", JOB_ANALYSIS_HUMAN_PROMPT),
        ],
    ).partial(
        format_instructions=parser.get_format_instructions(),
    )

    llm = _initialize_llm_client(llm_config)

    # Use StrOutputParser to get the raw string, then manually parse
    chain = prompt | llm | StrOutputParser()
    try:
        response_str = await chain.ainvoke(
            {
                "job_description": job_description,
                "resume_content_block": resume_content_block,
            },
        )

        parsed_json = parse_json_markdown(response_str)
        analysis = JobAnalysis.model_validate(parsed_json)

    except (json.JSONDecodeError, ValueError) as e:
        _msg = f"Failed to parse LLM response as JSON: {e!s}"
        log.exception(_msg)
        raise ValueError(
            "The AI service returned an unexpected response. Please try again.",
        ) from e

    _msg = "analyze_job_description returning"
    log.debug(_msg)
    return analysis, getattr(analysis, "introduction", None)


async def _refine_role_and_put_on_queue(
    job: RoleRefinementJob,
    semaphore: asyncio.Semaphore,
    event_queue: asyncio.Queue,
) -> None:
    """Refines a single role and puts progress/result events onto an asyncio.Queue.

    This function acts as a concurrent worker. It acquires a semaphore to limit
    concurrency, sends an 'in_progress' event to the queue, and calls the
    `refine_role` LLM function. If `refine_role` is successful, it puts the
    `role_refined` event on the queue. If `refine_role` raises an exception,
    this function allows the exception to propagate, which will be caught by
    the parent `TaskGroup`.

    Args:
        job (RoleRefinementJob): The refinement job containing the role, job analysis,
            LLM configuration, and original index.
        semaphore (asyncio.Semaphore): The semaphore to control concurrency.
        event_queue (asyncio.Queue): The queue to send events to.

    Returns:
        None

    Notes:
        1. This function is a coroutine.
        2. It waits to acquire the provided semaphore.
        3. Once acquired, it puts an 'in_progress' status message onto the
           `event_queue`.
        4. It calls `refine_role` to perform the actual LLM refinement.
        5. On success, it puts the `role_refined` event onto the queue.
        6. On failure, the exception from `refine_role` will cause this task to fail.
        7. The semaphore is released automatically by the `async with` block.

    """
    log.debug(
        "Waiting on semaphore for role refinement for index %d",
        job.original_index,
    )
    async with semaphore:
        role_title = f"{job.role.basics.title} @ {job.role.basics.company}"
        await event_queue.put(
            {
                "status": "in_progress",
                "message": f"Refining role '{role_title}'...",
            },
        )

        log.debug(
            "Semaphore acquired, refining role for index %d",
            job.original_index,
        )

        async def _progress_callback(message: str) -> None:
            await event_queue.put({"status": "in_progress", "message": message})

        refined_role = await refine_role(
            role=job.role,
            job_analysis=job.job_analysis,
            llm_config=job.llm_config,
            semaphore=semaphore,
            progress_callback=_progress_callback,
        )
        await event_queue.put(
            {
                "status": "role_refined",
                "data": refined_role.model_dump(mode="json"),
                "original_index": job.original_index,
            },
        )


async def async_refine_experience_section(
    resume_content: str,
    job_description: str,
    llm_config: LLMConfig,
    max_concurrency: int = 5,
    job_analysis: JobAnalysis | None = None,
    skip_indices: set[int] | None = None,
) -> AsyncGenerator[dict[str, Any], None]:
    """Orchestrates the CONCURRENT refinement of the 'experience' section of a resume.

    Args:
        resume_content (str): The full Markdown content of the resume.
        job_description (str): The job description to align the resume with.
        llm_config (LLMConfig): LLM configuration including endpoint, API key, and model
            name.
        max_concurrency (int): The maximum number of roles to refine in parallel.
        job_analysis (JobAnalysis | None): Optional cached job analysis. If provided,
            skips the analysis step.
        skip_indices (set[int] | None): Optional set of role indices to skip during
            refinement.

    Yields:
        dict[str, Any]: Status updates and refined role data.

    Notes:
        1. Yields progress messages for parsing the resume and analyzing the job
           description.
        2. Extracts experience information from the resume. If no roles are found, the
           function returns.
        3. If job_analysis is not provided, analyzes the job description to get key
           requirements, yielding a `job_analysis_complete` event. If provided, uses the
           cached analysis.
        4. Filters roles based on skip_indices - skipped roles yield a progress message
           and are not refined.
        5. Creates an `asyncio.Queue` for events and a `Semaphore` to limit concurrency.
        6. For each non-skipped role, a background task is created to perform
           refinement.
        7. Enters a loop to consume events from the queue, yielding them until all roles
           are processed.
        8. After the event loop, `asyncio.gather` is called to ensure all background
           tasks have completed.

    """
    _msg = "async_refine_experience_section starting"
    log.debug(_msg)

    # Initialize skip_indices to empty set if None
    skip_indices = skip_indices or set()

    # 1. Parse the experience section of the resume
    yield {"status": "in_progress", "message": "Parsing resume..."}
    log.debug("Parsing resume...")
    experience_info = extract_experience_info(resume_content)

    # 2. Analyze the job description (or use cached analysis)
    if job_analysis is None:
        yield {"status": "in_progress", "message": "Analyzing job description..."}
        log.debug("Analyzing job description...")

        job_analysis, _ = await analyze_job_description(
            job_description=job_description,
            llm_config=llm_config,
            resume_content_for_context=resume_content,
        )
    else:
        _msg = "Using cached job analysis"
        log.debug(_msg)

    yield {
        "status": "job_analysis_complete",
        "message": "Job analysis complete.",
        "job_analysis": job_analysis.model_dump(mode="json"),
    }

    # 3. Filter roles based on skip_indices
    roles_to_refine = [
        (i, role)
        for i, role in enumerate(experience_info.roles)
        if i not in skip_indices
    ]

    # Yield skip messages for skipped roles
    for index, role in enumerate(experience_info.roles):
        if index in skip_indices:
            role_title = (
                f"{role.basics.title} @ {role.basics.company}"
                if role.basics
                else f"Role {index}"
            )
            yield {
                "status": "in_progress",
                "message": f"Skipping role '{role_title}' (already refined)",
            }
            _msg = f"Skipping role at index {index} (already refined)"
            log.debug(_msg)

    # 4. Create and dispatch tasks for role refinement
    num_roles_to_refine = len(roles_to_refine)
    if num_roles_to_refine == 0:
        _msg = "No roles to refine after filtering"
        log.debug(_msg)
        return

    event_queue = asyncio.Queue()
    semaphore = asyncio.Semaphore(max_concurrency)

    tasks = []
    try:
        async with asyncio.TaskGroup() as tg:
            for index, role in roles_to_refine:
                job = RoleRefinementJob(
                    role=role,
                    job_analysis=job_analysis,
                    llm_config=llm_config,
                    original_index=index,
                )
                task = tg.create_task(
                    _refine_role_and_put_on_queue(
                        job=job,
                        semaphore=semaphore,
                        event_queue=event_queue,
                    ),
                )
                tasks.append(task)

            # 5. Yield events from the queue
            processed_count = 0
            while processed_count < num_roles_to_refine:
                event = await event_queue.get()
                if event.get("status") in ("role_refined",):
                    processed_count += 1

                yield event
                event_queue.task_done()
    except Exception as e:
        log.exception("Error during role refinement task group.")
        # If it's an ExceptionGroup with a single meaningful exception, unwrap it
        # to simplify error handling for the caller.
        _unwrap_exception_group(e)
    _msg = "async_refine_experience_section finishing"
    log.debug(_msg)


def _is_retryable_error(e: Exception) -> bool:
    """Determine if an error is retryable.

    Args:
        e (Exception): The exception to check.

    Returns:
        bool: True if the error is retryable, False otherwise.

    Notes:
        1. Retryable errors include: json.JSONDecodeError, TimeoutError, ConnectionError.
        2. Non-retryable errors include: AuthenticationError, pydantic.ValidationError,
           InvalidToken.
        3. Uses isinstance() checks to determine error type.

    """
    retryable_types = (json.JSONDecodeError, TimeoutError, ConnectionError)
    non_retryable_types = (AuthenticationError, ValidationError, InvalidToken)

    if isinstance(e, retryable_types):
        return True
    if isinstance(e, non_retryable_types):
        return False
    return False


def _truncate_for_log(text: str, max_len: int = 500) -> str:
    """Truncate text for logging purposes.

    Args:
        text (str): The text to potentially truncate.
        max_len (int): Maximum length before truncation. Defaults to 500.

    Returns:
        str: The original text if within max_len, otherwise truncated with "...".

    Notes:
        1. If text length exceeds max_len, truncates and appends "...".
        2. Otherwise returns the text unchanged.

    """
    if len(text) > max_len:
        return text[:max_len] + "..."
    return text


def _log_failed_attempt(
    role: Role,
    attempt: int,
    response: str,
    error: Exception,
    job_analysis: JobAnalysis,
) -> None:
    """Log a failed role refinement attempt.

    Args:
        role (Role): The role being refined.
        attempt (int): The attempt number that failed.
        response (str): The LLM response that caused the failure.
        error (Exception): The exception that occurred.
        job_analysis (JobAnalysis): The job analysis context.

    Returns:
        None

    Notes:
        1. Logs at DEBUG level.
        2. Includes truncated response using _truncate_for_log.
        3. Includes role context: company, title.
        4. Includes job analysis summary.
        5. Includes error type.
        6. Formats message into variable per CONVENTIONS.md (no f-strings in log call).

    """
    truncated_response = _truncate_for_log(response)
    job_summary = job_analysis.model_dump_json(indent=2)
    error_type = type(error).__name__

    _msg = (
        f"Failed attempt {attempt} for role '{role.basics.title} @ {role.basics.company}'. "
        f"Error type: {error_type}. "
        f"Job analysis: {job_summary}. Response: {truncated_response}"
    )
    log.debug(_msg)


def _create_error_context(role: Role, max_attempts: int) -> str:
    """Create a user-friendly error message for failed refinement.

    Args:
        role (Role): The role that failed to refine.
        max_attempts (int): The maximum number of attempts that were made.

    Returns:
        str: A formatted error message with instructions for the user.

    Notes:
        1. Returns formatted error message with role title and company.
        2. Includes the number of attempts made.
        3. Mentions potential AI service issues.
        4. Provides instruction to click Start Refinement to resume.

    """
    _msg = (
        f"Unable to refine '{role.basics.title} @ {role.basics.company}' "
        f"after {max_attempts} attempts. The AI service may be experiencing issues. "
        "Click Start Refinement to resume."
    )
    return _msg


async def _attempt_refine_role(
    chain: Any,
    job_analysis_json: str,
    role_json: str,
) -> tuple[bool, RefinedRole | None, Exception | None]:
    """Attempt a single LLM refinement invocation.

    Args:
        chain (Any): The LangChain runnable chain to invoke.
        job_analysis_json (str): JSON string of the job analysis.
        role_json (str): JSON string of the role to refine.

    Returns:
        tuple[bool, RefinedRole | None, Exception | None]: A tuple containing:
            - success (bool): True if the attempt succeeded, False otherwise.
            - result (RefinedRole | None): The refined role if successful, None otherwise.
            - error (Exception | None): The exception if failed, None otherwise.

    Notes:
        1. Invokes the chain asynchronously with job_analysis_json and role_json.
        2. Parses the response using _parse_json_with_fix for robustness.
        3. Validates the parsed JSON against the RefinedRole model.
        4. Returns (True, refined_role, None) on success.
        5. Catches exceptions and returns (False, None, error) on failure.
        6. Re-raises AuthenticationError immediately as it is non-retryable.

    Network access:
        - This function makes a network request to the LLM endpoint.

    """
    try:
        response_str = await chain.ainvoke(
            {
                "job_analysis_json": job_analysis_json,
                "role_json": role_json,
            },
        )
        parsed_json = _parse_json_with_fix(response_str)
        refined_role = RefinedRole.model_validate(parsed_json)
        return True, refined_role, None
    except AuthenticationError:
        raise
    except Exception as e:
        return False, None, e


async def _handle_retry_delay(
    attempt: int,
    role: Role,
    response_str: str,
    error: Exception,
    job_analysis: JobAnalysis,
    semaphore: asyncio.Semaphore | None,
    progress_callback: Callable[[str], Awaitable[None]] | None,
) -> None:
    """Handle the delay and logging between retry attempts.

    Args:
        attempt (int): The current attempt number (0-indexed).
        role (Role): The role being refined.
        response_str (str): The LLM response string.
        error (Exception): The error that occurred.
        job_analysis (JobAnalysis): The job analysis context.
        semaphore (asyncio.Semaphore | None): Optional semaphore to release during delay.
        progress_callback (Callable[[str], Awaitable[None]] | None): Optional callback
            for progress updates.

    Returns:
        None

    Notes:
        1. Logs the failed attempt using _log_failed_attempt.
        2. Calls progress_callback with retry message if provided.
        3. Releases semaphore if provided.
        4. Sleeps for 3 seconds.
        5. Re-acquires semaphore if provided.

    """
    _log_failed_attempt(
        role=role,
        attempt=attempt + 1,
        response=response_str,
        error=error,
        job_analysis=job_analysis,
    )

    if progress_callback is not None:
        _retry_msg = f"Retrying role refinement for '{role.basics.title} @ {role.basics.company}' (attempt {attempt + 2}/3)..."
        await progress_callback(_retry_msg)

    if semaphore is not None:
        semaphore.release()

    await asyncio.sleep(3)

    if semaphore is not None:
        await semaphore.acquire()


async def _process_refinement_error(
    attempt: int,
    error: Exception,
    role: Role,
    response_str: str,
    job_analysis: JobAnalysis,
    semaphore: asyncio.Semaphore | None,
    progress_callback: Callable[[str], Awaitable[None]] | None,
) -> bool:
    """Process an error from a refinement attempt and decide whether to retry.

    Args:
        attempt (int): The current attempt number (0-indexed).
        error (Exception): The error that occurred.
        role (Role): The role being refined.
        response_str (str): The LLM response string.
        job_analysis (JobAnalysis): The job analysis context.
        semaphore (asyncio.Semaphore | None): Optional semaphore for retry delays.
        progress_callback (Callable[[str], Awaitable[None]] | None): Optional callback
            for progress updates.

    Returns:
        bool: True if should retry, False if max attempts reached.

    Raises:
        Exception: Re-raises the error if it is not retryable.

    Notes:
        1. Checks if the error is retryable using _is_retryable_error.
        2. If not retryable, re-raises the error immediately.
        3. If retryable and not the last attempt, calls _handle_retry_delay.
        4. Returns True if retry should proceed, False if max attempts reached.

    """
    if not _is_retryable_error(error):
        raise error

    if attempt < 2:  # Not the last attempt
        await _handle_retry_delay(
            attempt=attempt,
            role=role,
            response_str=response_str,
            error=error,
            job_analysis=job_analysis,
            semaphore=semaphore,
            progress_callback=progress_callback,
        )
        return True
    return False


async def refine_role(
    role: Role,
    job_analysis: JobAnalysis,
    llm_config: LLMConfig,
    semaphore: asyncio.Semaphore | None = None,
    progress_callback: Callable[[str], Awaitable[None]] | None = None,
) -> RefinedRole:
    """Uses an LLM to refine a single resume Role based on a job analysis.

    Args:
        role (Role): The structured Role object to refine.
        job_analysis (JobAnalysis): The structured job analysis to align with.
        llm_config (LLMConfig): LLM configuration including endpoint, API key, and model
            name.
        semaphore (asyncio.Semaphore | None): Optional semaphore to release/reacquire
            during retry delays.
        progress_callback (Callable[[str], Awaitable[None]] | None): Optional callback
            for progress updates during retries.

    Returns:
        RefinedRole: The refined and validated Role object.

    Raises:
        ValueError: If the LLM response is not valid JSON or fails Pydantic validation after all retries.
        AuthenticationError: If authentication fails (not retryable).

    Notes:
        1. Set up a PydanticOutputParser for structured output based on the `RefinedRole` model.
        2. Serialize the input role and job_analysis objects to JSON strings.
        3. Create a PromptTemplate with instructions for the LLM.
        4. Initialize the ChatOpenAI client.
        5. Create a chain combining the prompt, LLM, and a string output parser.
        6. Attempt the LLM call up to 3 times using _attempt_refine_role().
        7. On failure, call _process_refinement_error() to decide whether to retry.
        8. If all attempts fail, raise ValueError with `_create_error_context()` message.
        9. Preserves the original `inclusion_status` of the role, as this is a user-controlled setting.
        10. Return the validated `RefinedRole` object.

    Network access:
        - This function makes a network request to the LLM endpoint.

    """
    _msg = "refine_role starting"
    log.debug(_msg)

    parser = PydanticOutputParser(pydantic_object=RefinedRole)

    prompt = ChatPromptTemplate.from_messages(
        [
            ("system", ROLE_REFINE_SYSTEM_PROMPT),
            ("human", ROLE_REFINE_HUMAN_PROMPT),
        ],
    ).partial(format_instructions=parser.get_format_instructions())

    llm = _initialize_llm_client(llm_config)

    chain = prompt | llm | StrOutputParser()

    # Serialize the Pydantic objects to JSON strings
    role_json = role.model_dump_json(indent=2)
    job_analysis_json = job_analysis.model_dump_json(indent=2)

    last_error: Exception | None = None
    refined_role: RefinedRole | None = None
    response_str: str = ""

    for attempt in range(3):
        success, result, error = await _attempt_refine_role(
            chain=chain,
            job_analysis_json=job_analysis_json,
            role_json=role_json,
        )

        if success:
            refined_role = result
            break

        # Handle failure and decide whether to retry
        # error is never None when success is False
        last_error = error  # type: ignore[assignment]
        should_retry = await _process_refinement_error(
            attempt=attempt,
            error=last_error,  # type: ignore[arg-type]
            role=role,
            response_str=response_str,
            job_analysis=job_analysis,
            semaphore=semaphore,
            progress_callback=progress_callback,
        )

        if not should_retry:
            break

    if refined_role is None:
        _error_msg = _create_error_context(role, 3)
        raise ValueError(_error_msg) from last_error

    # Preserve the original inclusion status, as the AI should not decide this.
    refined_role.basics.inclusion_status = role.basics.inclusion_status

    _msg = "refine_role returning"
    log.debug(_msg)
    return refined_role


def _invoke_chain_and_parse(chain: Any, pydantic_model: Any, **kwargs: Any) -> Any:
    """Invokes a LangChain chain, gets content, parses JSON, and validates with Pydantic.

    Args:
        chain (Any): The LangChain runnable chain to invoke.
        pydantic_model (Any): The Pydantic model to validate the parsed JSON against.
        **kwargs (Any): Keyword arguments to pass to the chain's invoke method.

    Returns:
        Any: An instance of the `pydantic_model` populated with the parsed data.

    Raises:
        ValueError: If parsing or validation fails.

    Notes:
        1. Invokes the provided LangChain `chain` with the given `kwargs`.
        2. Extracts the content string from the result.
        3. Parses the content string as JSON using `_parse_json_with_fix`.
        4. Validates the parsed JSON against the `pydantic_model`.
        5. Returns the validated Pydantic model instance.
        6. On JSON decoding or Pydantic validation errors, logs the exception
           and raises a `ValueError`.

    """
    _msg = "_invoke_chain_and_parse starting"
    log.debug(_msg)

    try:
        result = chain.invoke(kwargs)
        result_str = result.content
        parsed_json = _parse_json_with_fix(result_str)
        validated_model = pydantic_model.model_validate(parsed_json)
    except (json.JSONDecodeError, ValidationError) as e:
        _msg = f"Failed to parse or validate LLM response: {e!s}"
        log.exception(_msg)
        raise ValueError(
            "The AI service returned an unexpected response. Please try again.",
        ) from e

    _msg = "_invoke_chain_and_parse returning"
    log.debug(_msg)
    return validated_model


def _generate_introduction_from_analysis(
    job_analysis_json: str,
    resume_content: str,
    llm: ChatOpenAI,
    original_banner: str | None = None,
) -> str:
    """Orchestrates the resume analysis and introduction synthesis steps.

    This function is part of a multi-step, fact-based introduction generation process.
    It takes a pre-analyzed set of job requirements and uses an LLM to analyze the
    entirety of the candidate's resume for factual evidence that supports their
    qualifications for the role. It then synthesizes an introduction based *only*
    on that evidence.

    Args:
        job_analysis_json (str): A JSON string representing the pre-analyzed job requirements,
                                 conforming to the `JobKeyRequirements` model.
        resume_content (str): The full Markdown content of the resume, which will be scoured for evidence.
        llm (ChatOpenAI): An initialized ChatOpenAI client instance.
        original_banner (str | None): The original banner text from the resume, to provide context to the LLM.

    Returns:
        str: The generated introduction as a Markdown-formatted bulleted list,
             or an empty string if generation fails.

    Notes:
        1.  **Step 1: Resume Analysis**: Creates a chain with
            `INTRO_ANALYZE_RESUME_PROMPT`. This prompt instructs the LLM to act as a
            recruiter, analyzing the `resume_content` to find factual evidence for each
            requirement in `job_analysis_json`. The output is parsed into a
            `CandidateAnalysis` model.
        2.  **Step 2: Introduction Synthesis**: Creates a chain with
            `INTRO_SYNTHESIZE_INTRODUCTION_PROMPT`. This prompt takes the evidence from
            the previous step and synthesizes a concise, compelling introduction. It is
            strictly instructed to only use the provided evidence. The output is parsed
            into a `GeneratedIntroduction` model.
        3.  Extracts the `strengths` list from the final Pydantic object and formats it
            as a Markdown bulleted list.
        4.  Handles JSON decoding and Pydantic validation errors by logging and
            returning an empty string.
        5.  This function performs multiple network requests to the configured LLM
            endpoint.

    """
    _msg = "_generate_introduction_from_analysis starting"
    log.debug(_msg)

    try:
        # Step 2 from original: Resume Analysis
        resume_analysis_parser = PydanticOutputParser(pydantic_object=CandidateAnalysis)
        resume_analysis_prompt = ChatPromptTemplate.from_messages(
            [
                ("system", INTRO_ANALYZE_RESUME_SYSTEM_PROMPT),
                ("human", INTRO_ANALYZE_RESUME_HUMAN_PROMPT),
            ],
        ).partial(format_instructions=resume_analysis_parser.get_format_instructions())
        resume_analysis_chain = resume_analysis_prompt | llm
        candidate_analysis = _invoke_chain_and_parse(
            resume_analysis_chain,
            CandidateAnalysis,
            resume_content=resume_content,
            job_requirements=job_analysis_json,
            original_banner=original_banner or "",
        )

        # Step 3 from original: Synthesis
        synthesis_parser = PydanticOutputParser(pydantic_object=GeneratedIntroduction)
        synthesis_prompt = ChatPromptTemplate.from_messages(
            [
                ("system", INTRO_SYNTHESIZE_INTRODUCTION_SYSTEM_PROMPT),
                ("human", INTRO_SYNTHESIZE_INTRODUCTION_HUMAN_PROMPT),
            ],
        ).partial(format_instructions=synthesis_parser.get_format_instructions())
        synthesis_chain = synthesis_prompt | llm
        generated_introduction = _invoke_chain_and_parse(
            synthesis_chain,
            GeneratedIntroduction,
            candidate_analysis=candidate_analysis.model_dump_json(),
        )

        strengths = generated_introduction.strengths
        introduction = "\n".join(f"- {s}" for s in strengths)

    except ValueError as e:
        _msg = f"Failed during introduction generation chain: {e!s}"
        log.exception(_msg)
        introduction = ""

    _msg = "_generate_introduction_from_analysis returning"
    log.debug(_msg)
    return introduction


def generate_introduction_from_resume(
    resume_content: str,
    job_description: str,
    llm_config: LLMConfig,
    original_banner: str | None = None,
) -> str:
    """Generates a resume introduction using a multi-step, fact-based LLM chain.

    This function orchestrates a sequence of LLM calls to produce a tailored
    introduction (or "banner") for a resume based on a specific job description.
    The process is designed to be fact-based, meaning the LLM first analyzes the
    job, then scours the *entire resume* for evidence supporting the candidate's
    qualifications, and finally writes an introduction based *only* on that evidence.

    Args:
        resume_content (str): The full Markdown content of the resume to be analyzed.
        job_description (str): The job description to align the introduction with.
        llm_config (LLMConfig): Configuration for the LLM client.
        original_banner (str | None): The original banner text from the resume, to provide context to the LLM.

    Returns:
        str: The generated introduction as a Markdown string, or an empty string if generation fails.

    Notes:
        1.  Initializes a ChatOpenAI client using the provided `llm_config`.
        2.  **Step 1: Job Analysis**: Creates and invokes a chain with
            `INTRO_ANALYZE_JOB_PROMPT` to extract key skills and priorities from the
            `job_description`.
        3.  **Step 2 & 3 (Delegation)**: Calls `_generate_introduction_from_analysis` with
            the job analysis result. This sub-process performs the detailed, fact-finding
            resume analysis and the final introduction synthesis.
        4.  Handles exceptions during the initial job analysis step and returns an empty
            string on failure.
        5.  This function performs multiple network requests to the configured LLM
            endpoint.

    """
    _msg = "generate_introduction_from_resume starting"
    log.debug(_msg)

    # Initialize LLM client
    llm = _initialize_llm_client(llm_config)

    try:
        # Step 1: Job Analysis
        job_analysis_parser = PydanticOutputParser(pydantic_object=JobKeyRequirements)
        job_analysis_prompt = ChatPromptTemplate.from_messages(
            [
                ("system", INTRO_ANALYZE_JOB_SYSTEM_PROMPT),
                ("human", INTRO_ANALYZE_JOB_HUMAN_PROMPT),
            ],
        ).partial(format_instructions=job_analysis_parser.get_format_instructions())
        job_analysis_chain = job_analysis_prompt | llm
        job_analysis = _invoke_chain_and_parse(
            job_analysis_chain,
            JobKeyRequirements,
            job_description=job_description,
        )

    except ValueError as e:
        _msg = f"Failed during introduction generation (Job Analysis step): {e!s}"
        log.exception(_msg)
        return ""

    introduction = _generate_introduction_from_analysis(
        job_analysis_json=job_analysis.model_dump_json(),
        resume_content=resume_content,
        llm=llm,
        original_banner=original_banner,
    )

    _msg = "generate_introduction_from_resume returning"
    log.debug(_msg)
    return introduction


def _extract_cross_section_evidence(
    resume_content: str, job_analysis: JobAnalysis
) -> list[CrossSectionEvidence]:
    """Extract relevant evidence from Education, Certifications, and Projects sections.

    This function parses the resume content to identify facts from non-experience
    sections that support the candidate's qualifications for the job.

    Args:
        resume_content: The full Markdown content of the resume.
        job_analysis: The job analysis containing key skills and themes.

    Returns:
        list[CrossSectionEvidence]: A list of evidence items from cross-section sources,
            ordered by relevance score (highest first).

    Notes:
        1. Parses Education section for degrees relevant to job requirements.
        2. Parses Certifications section for credentials matching job skills.
        3. Parses Projects section for demonstrable skills.
        4. Scores each piece of evidence by relevance to job_analysis.
        5. Returns evidence sorted by relevance_score descending.
        6. This is a heuristic extraction; scores are approximate.

    """
    _msg = "_extract_cross_section_evidence starting"
    log.debug(_msg)

    evidence_list: list[CrossSectionEvidence] = []
    job_skills_lower = [skill.lower() for skill in job_analysis.key_skills]
    job_themes_lower = [
        theme.lower() for theme in job_analysis.themes + job_analysis.inferred_themes
    ]

    # Extract Education section
    education_section = _extract_section_content(resume_content, "education")
    if education_section:
        # Look for degree mentions that might be relevant
        degree_keywords = [
            "bachelor",
            "master",
            "phd",
            "doctorate",
            "bs",
            "ms",
            "ba",
            "ma",
            "mba",
        ]
        for line in education_section.split("\n"):
            line_lower = line.lower()
            if any(keyword in line_lower for keyword in degree_keywords):
                # Score based on relevance to job
                relevance = _calculate_education_relevance(
                    line, job_skills_lower, job_themes_lower
                )
                if relevance >= 5:  # Only include if reasonably relevant
                    evidence_list.append(
                        CrossSectionEvidence(
                            section_type="Education",
                            content=line.strip(),
                            relevance_score=relevance,
                        ),
                    )

    # Extract Certifications section
    certifications_section = _extract_section_content(resume_content, "certifications")
    if certifications_section:
        for line in certifications_section.split("\n"):
            line_stripped = line.strip()
            if line_stripped and not line_stripped.startswith("#"):
                relevance = _calculate_certification_relevance(
                    line_stripped, job_skills_lower
                )
                if relevance >= 6:  # Certifications should be fairly relevant
                    evidence_list.append(
                        CrossSectionEvidence(
                            section_type="Certification",
                            content=line_stripped,
                            relevance_score=relevance,
                        ),
                    )

    # Extract Projects section
    projects_section = _extract_section_content(resume_content, "projects")
    if projects_section:
        # Split by project headers (### or similar)
        project_chunks = _split_projects_section(projects_section)
        for chunk in project_chunks:
            relevance = _calculate_project_relevance(
                chunk, job_skills_lower, job_themes_lower
            )
            if relevance >= 5:
                evidence_list.append(
                    CrossSectionEvidence(
                        section_type="Project",
                        content=chunk.strip()[:200],  # Truncate long content
                        relevance_score=relevance,
                    ),
                )

    # Sort by relevance score descending
    evidence_list.sort(key=lambda x: x.relevance_score, reverse=True)

    _msg = (
        f"_extract_cross_section_evidence returning {len(evidence_list)} evidence items"
    )
    log.debug(_msg)
    return evidence_list


def _extract_section_content(resume_content: str, section_name: str) -> str | None:
    """Extract the raw content of a section from resume markdown.

    Args:
        resume_content: The full Markdown content of the resume.
        section_name: The name of the section to extract (e.g., 'education').

    Returns:
        str | None: The content of the section, or None if not found.

    Notes:
        1. Looks for a header matching # SectionName (case-insensitive).
        2. Captures all content until the next # header or end of content.
        3. Returns None if section is not found.

    """
    lines = resume_content.splitlines()
    section_header = f"# {section_name.lower()}"
    in_section = False
    captured_lines = []

    for line in lines:
        stripped = line.strip().lower()
        # Check for section header
        if stripped.startswith(section_header) and not stripped.startswith("## "):
            in_section = True
            continue
        # Check for next main section
        if in_section and stripped.startswith("# ") and not stripped.startswith("## "):
            break
        if in_section:
            captured_lines.append(line)

    if captured_lines:
        return "\n".join(captured_lines).strip()
    return None


def _calculate_education_relevance(
    education_line: str, job_skills_lower: list[str], job_themes_lower: list[str]
) -> int:
    """Calculate relevance score for an education entry.

    Args:
        education_line: A line from the education section.
        job_skills_lower: Lowercase job skills for matching.
        job_themes_lower: Lowercase job themes for matching.

    Returns:
        int: Relevance score from 1-10.

    Notes:
        1. Base score of 5 for any degree.
        2. +2 if field of study matches job skills/themes.
        3. +1 if advanced degree (Master's/PhD) and job suggests seniority.
        4. Capped at 10.

    """
    score = 5
    line_lower = education_line.lower()

    # Check for field relevance
    for skill in job_skills_lower:
        if skill in line_lower:
            score += 2
            break

    for theme in job_themes_lower:
        if theme in line_lower:
            score += 1
            break

    # Boost for advanced degrees if job seems senior
    if any(term in line_lower for term in ["master", "phd", "doctorate", "mba"]):
        if any(
            term in " ".join(job_themes_lower)
            for term in ["senior", "lead", "principal", "advanced"]
        ):
            score += 1

    return min(score, 10)


def _calculate_certification_relevance(
    cert_line: str, job_skills_lower: list[str]
) -> int:
    """Calculate relevance score for a certification entry.

    Args:
        cert_line: A line from the certifications section.
        job_skills_lower: Lowercase job skills for matching.

    Returns:
        int: Relevance score from 1-10.

    Notes:
        1. Base score of 6 for any certification.
        2. +3 if certification directly matches a job skill.
        3. Capped at 10.

    """
    score = 6
    line_lower = cert_line.lower()

    for skill in job_skills_lower:
        if skill in line_lower:
            score += 3
            break

    return min(score, 10)


def _calculate_project_relevance(
    project_chunk: str, job_skills_lower: list[str], job_themes_lower: list[str]
) -> int:
    """Calculate relevance score for a project entry.

    Args:
        project_chunk: A chunk of text describing a project.
        job_skills_lower: Lowercase job skills for matching.
        job_themes_lower: Lowercase job themes for matching.

    Returns:
        int: Relevance score from 1-10.

    Notes:
        1. Base score of 4 for any project.
        2. +2 for each matching job skill (up to +4).
        3. +1 for each matching theme (up to +2).
        4. Capped at 10.

    """
    score = 4
    chunk_lower = project_chunk.lower()

    skill_matches = sum(1 for skill in job_skills_lower if skill in chunk_lower)
    score += min(skill_matches * 2, 4)

    theme_matches = sum(1 for theme in job_themes_lower if theme in chunk_lower)
    score += min(theme_matches, 2)

    return min(score, 10)


def _split_projects_section(projects_section: str) -> list[str]:
    """Split the projects section into individual project chunks.

    Args:
        projects_section: The content of the projects section.

    Returns:
        list[str]: List of project chunks.

    Notes:
        1. Splits on ### headers (project titles).
        2. If no headers found, treats entire section as one project.

    """
    lines = projects_section.splitlines()
    chunks = []
    current_chunk = []

    for line in lines:
        if line.strip().startswith("### "):
            if current_chunk:
                chunks.append("\n".join(current_chunk))
                current_chunk = []
        current_chunk.append(line)

    if current_chunk:
        chunks.append("\n".join(current_chunk))

    return chunks if chunks else [projects_section]


def _format_role_data_for_banner(
    refined_roles: list[RefinedRoleRecord],
) -> list[dict[str, Any]]:
    """Format refined role records for banner generation input.

    Args:
        refined_roles: List of refined role records from the running log.

    Returns:
        list[dict[str, Any]]: Formatted role data suitable for LLM prompt.

    Notes:
        1. Extracts key information: company, title, description, skills.
        2. Structures data to emphasize skills with company associations.
        3. Orders roles by recency (using original_index as proxy).

    """
    _msg = "_format_role_data_for_banner starting"
    log.debug(_msg)

    formatted_roles = []
    for role in refined_roles:
        role_data = {
            "company": role.company,
            "title": role.title,
            "description": role.refined_description[:300]
            if len(role.refined_description) > 300
            else role.refined_description,  # Truncate if needed
            "skills": role.relevant_skills,
            "position": role.original_index,
        }
        formatted_roles.append(role_data)

    # Sort by position (original index) to maintain resume order
    formatted_roles.sort(key=lambda x: x["position"])

    _msg = (
        f"_format_role_data_for_banner returning {len(formatted_roles)} formatted roles"
    )
    log.debug(_msg)
    return formatted_roles


def _invoke_banner_generation_chain(
    llm: ChatOpenAI,
    job_analysis: JobAnalysis,
    refined_roles: list[RefinedRoleRecord],
    cross_section_evidence: list[CrossSectionEvidence],
    original_banner: str | None,
) -> GeneratedBanner | None:
    """Invoke the LLM chain for banner generation.

    Args:
        llm: Initialized ChatOpenAI client.
        job_analysis: The job analysis for context.
        refined_roles: List of refined role records.
        cross_section_evidence: Cross-section evidence for context.
        original_banner: Original banner for context (optional).

    Returns:
        GeneratedBanner | None: The generated banner or None if generation fails.

    Notes:
        1. Creates a prompt with BANNER_GENERATION_SYSTEM_PROMPT.
        2. Formats all input data as JSON strings.
        3. Invokes the chain and parses the response.
        4. Validates against GeneratedBanner model.
        5. Returns None on any error.

    """
    _msg = "_invoke_banner_generation_chain starting"
    log.debug(_msg)

    try:
        parser = PydanticOutputParser(pydantic_object=GeneratedBanner)

        prompt = ChatPromptTemplate.from_messages(
            [
                ("system", BANNER_GENERATION_SYSTEM_PROMPT),
                ("human", BANNER_GENERATION_HUMAN_PROMPT),
            ],
        ).partial(format_instructions=parser.get_format_instructions())

        chain = prompt | llm | StrOutputParser()

        # Format input data
        formatted_roles = _format_role_data_for_banner(refined_roles)

        response_str = chain.invoke(
            {
                "job_analysis_json": job_analysis.model_dump_json(),
                "refined_roles_json": json.dumps(formatted_roles, indent=2),
                "cross_section_evidence_json": json.dumps(
                    [e.model_dump() for e in cross_section_evidence], indent=2
                ),
                "original_banner": original_banner or "",
            },
        )

        parsed_json = _parse_json_with_fix(response_str)
        banner = GeneratedBanner.model_validate(parsed_json)

        _msg = "_invoke_banner_generation_chain returning successfully"
        log.debug(_msg)
        return banner

    except Exception as e:
        _msg = f"Banner generation chain failed: {e!s}"
        log.exception(_msg)
        return None


def generate_banner_from_running_log(
    running_log: RunningLog,
    original_resume_content: str,
    llm_config: LLMConfig,
    original_banner: str | None = None,
) -> str:
    """Generate a resume banner using refined data from the RunningLog.

    This is the primary function for generating banners in the new checkpoint-based
    workflow. It uses the refined role data and cross-section evidence to create
    a semantically coherent, role-centric banner.

    Args:
        running_log: The running log containing refined roles and job analysis.
        original_resume_content: The original resume content for cross-section extraction.
        llm_config: Configuration for the LLM client.
        original_banner: The original banner text for context (optional).

    Returns:
        str: The generated banner as a Markdown-formatted string, or empty string if generation fails.

    Notes:
        1. Validates that running_log has job_analysis and refined_roles.
        2. Extracts cross-section evidence from the original resume.
        3. Initializes the LLM client.
        4. Invokes the banner generation chain.
        5. Formats the result as Markdown bullet points.
        6. Falls back to empty string if generation fails.

    """
    _msg = "generate_banner_from_running_log starting"
    log.debug(_msg)

    # Validate inputs
    if not running_log.job_analysis:
        _msg = "Running log has no job_analysis, cannot generate banner"
        log.warning(_msg)
        return ""

    if not running_log.refined_roles:
        _msg = "Running log has no refined_roles, cannot generate banner"
        log.warning(_msg)
        return ""

    # Extract cross-section evidence
    cross_section_evidence = _extract_cross_section_evidence(
        resume_content=original_resume_content,
        job_analysis=running_log.job_analysis,
    )

    # Initialize LLM
    llm = _initialize_llm_client(llm_config)

    # Generate banner
    banner = _invoke_banner_generation_chain(
        llm=llm,
        job_analysis=running_log.job_analysis,
        refined_roles=running_log.refined_roles,
        cross_section_evidence=cross_section_evidence,
        original_banner=original_banner,
    )

    if banner is None:
        _msg = "Banner generation returned None"
        log.warning(_msg)
        return ""

    # Format the banner as Markdown
    banner_lines = []
    for bullet in banner.bullets:
        banner_lines.append(f"- **{bullet.category}:** {bullet.description}")

    # Add education bullet if present and relevant
    if banner.education_bullet:
        banner_lines.append(
            f"- **{banner.education_bullet.category}:** {banner.education_bullet.description}"
        )

    result = "\n".join(banner_lines)

    _msg = "generate_banner_from_running_log returning"
    log.debug(_msg)
    return result
